package dk.mzw.accelemation

import dk.mzw.accelemation.internal.Internal._

object Language {

    type Time = R
    type Color = Vec4

    type Image = R => R => Color
    type Animation = Time => Image

    def if_[A <: Typed[A]](condition : B, whenTrue : Typed[A], whenFalse : Typed[A]) : Typed[A] = whenTrue.make(If(condition.untyped, whenTrue.untyped, whenFalse.untyped))
    def rgba(r : R, g : R, b : R, a : R) : Color = Vec4(r, g, b, a)

    implicit def liftUniformB(uniform : Uniform[Boolean]) : B = B(UniformU(uniform, "bool"))
    implicit def liftUniformR(uniform : Uniform[Double]) : R = R(UniformU(uniform, "float"))
    implicit def liftUniformI(uniform : Uniform[Int]) : I = I(UniformU(uniform, "int"))
    implicit def liftUniformVec2(uniform : Uniform[(Double, Double)]) : Vec2 = Vec2(UniformU(uniform, "vec2"))
    implicit def liftUniformVec3(uniform : Uniform[(Double, Double, Double)]) : Vec3 = Vec3(UniformU(uniform, "vec3"))
    implicit def liftUniformVec4(uniform : Uniform[(Double, Double, Double, Double)]) : Vec4 = Vec4(UniformU(uniform, "vec4"))
    implicit def liftUniformBVec2(uniform : Uniform[(Boolean, Boolean)]) : BVec2 = BVec2(UniformU(uniform, "vec2"))
    implicit def liftUniformBVec3(uniform : Uniform[(Boolean, Boolean, Boolean)]) : BVec3 = BVec3(UniformU(uniform, "vec3"))
    implicit def liftUniformBVec4(uniform : Uniform[(Boolean, Boolean, Boolean, Boolean)]) : BVec4 = BVec4(UniformU(uniform, "vec4"))
    implicit def liftUniformIVec2(uniform : Uniform[(Int, Int)]) : IVec2 = IVec2(UniformU(uniform, "vec2"))
    implicit def liftUniformIVec3(uniform : Uniform[(Int, Int, Int)]) : IVec3 = IVec3(UniformU(uniform, "vec3"))
    implicit def liftUniformIVec4(uniform : Uniform[(Int, Int, Int, Int)]) : IVec4 = IVec4(UniformU(uniform, "vec4"))

    /**
      * Grant access to the internal untyped AST
      */
    def untyped(t : Typed[_]) : Untyped = t.untyped

    implicit def doubleToR(r : Double) : R = R(ConstantFloat(r))
    implicit def intToR(r : Int) : R = R(ConstantFloat(r))
    implicit def intToI(i : Int) : I = I(i)

    // GLSL implicit conversions
    implicit def iToR(i : I) : R = R(i.untyped)
    // TODO ivec to vec

    // implicit constructors used for bind
    case class Meta[T](
        make : Untyped => T,
        glslTypeName : String,
        untyped : T => Untyped
    )

    implicit def metaR = Meta[R](R(_), "float", {_.untyped})
    implicit def metaB = Meta[B](B(_), "bool", {_.untyped})
    implicit def metaI = Meta[I](I(_), "int", {_.untyped})
    implicit def metaVec2 = Meta[Vec2](Vec2(_), "vec2", {_.untyped})
    implicit def metaVec3 = Meta[Vec3](Vec3(_), "vec3", {_.untyped})
    implicit def metaVec4 = Meta[Vec4](Vec4(_), "vec4", {_.untyped})
    implicit def metaBVec2 = Meta[BVec2](BVec2(_), "bvec2", {_.untyped})
    implicit def metaBVec3 = Meta[BVec3](BVec3(_), "bvec3", {_.untyped})
    implicit def metaBVec4 = Meta[BVec4](BVec4(_), "bvec4", {_.untyped})
    implicit def metaIVec2 = Meta[IVec2](IVec2(_), "ivec2", {_.untyped})
    implicit def metaIVec3 = Meta[IVec3](IVec3(_), "ivec3", {_.untyped})
    implicit def metaIVec4 = Meta[IVec4](IVec4(_), "ivec4", {_.untyped})

    sealed trait HasUntyped {
        protected[Language] val untyped : Untyped
    }

    /**
      * Any supported GLSL type
      */
    sealed trait Typed[Self <: Typed[Self]] extends HasUntyped { /*this : Self =>*/
        protected[Language] val make : Untyped => Self
        protected[Language] val typeName : String

        def ===(b : Self) : B = B(Infix("==", untyped, b.untyped))
        def !=(b : Self) : B = B(Infix("!=", untyped, b.untyped))

        def bind[T <: Typed[T]](f : Self => T) (implicit meta : Meta[T]) : T = {
            def body(a: Untyped) : Untyped = f(make(a)).untyped
            meta.make(Bind(typeName, untyped, body))
        }

        def flatMap[T <: Typed[T]](f : Self => T) (implicit meta : Meta[T]) : T = bind(f)(meta)
        def map[T <: Typed[T]](f : Self => T) (implicit meta : Meta[T]) : T = bind(f)(meta)

    }

        /**
      *  Models a GLSL vec2, vec3, vec4, bvec2, bvec3, bvec4, ivec2, ivec3 or ivec4
      */
    sealed trait XVec[Self1, Self2, Self3, Self4] extends HasUntyped {
        protected[Language] val make1 : Untyped => Self1
        protected[Language] val make2 : Untyped => Self2
        protected[Language] val make3 : Untyped => Self3
        protected[Language] val make4 : Untyped => Self4
    }


    /**
      *  Models a GLSL float, vec2, vec3 or vec4
      */
    sealed trait FloatN[Self <: FloatN[Self]] extends Typed[Self] {
        def +(b : Self) : Self = make(Infix("+", untyped, b.untyped))
        def -(b : Self) : Self = make(Infix("-", untyped, b.untyped))
        def *(b : Self) : Self = make(Infix("*", untyped, b.untyped))
        def /(b : Self) : Self = make(Infix("/", untyped, b.untyped))
        def unary_-() : Self = make(Prefix("-", untyped))
    }

    /**
      * Models a GLSL vec2, vec3 or vec4
      */
    sealed trait Vec[Self <: Vec[Self]] extends FloatN[Self] with XVec[R, Vec2, Vec3, Vec4] {
        protected[Language] val make1 = {u : Untyped => R(u)}
        protected[Language] val make2 = {u : Untyped => Vec2(u)}
        protected[Language] val make3 = {u : Untyped => Vec3(u)}
        protected[Language] val make4 = {u : Untyped => Vec4(u)}

        def magnitude : R = R(Call("length", List(untyped)))
        def normalize : Self = make(Call("normalize", List(untyped)))

        def +(b : R) : Self = make(Infix("+", untyped, b.untyped))
        def -(b : R) : Self = make(Infix("-", untyped, b.untyped))
        def *(b : R) : Self = make(Infix("*", untyped, b.untyped))
        def /(b : R) : Self = make(Infix("/", untyped, b.untyped))
    }

    /**
      * Models a GLSL ivec2, ivec3 or ivec4
      */
    sealed trait IVec[Self <: IVec[Self]] extends Typed[Self] with XVec[I, IVec2, IVec3, IVec4] {
        protected[Language] val make1 = {u : Untyped => I(u)}
        protected[Language] val make2 = {u : Untyped => IVec2(u)}
        protected[Language] val make3 = {u : Untyped => IVec3(u)}
        protected[Language] val make4 = {u : Untyped => IVec4(u)}

        def +(b : I) : Self = make(Infix("+", untyped, b.untyped))
        def -(b : I) : Self = make(Infix("-", untyped, b.untyped))
        def *(b : I) : Self = make(Infix("*", untyped, b.untyped))
        def /(b : I) : Self = make(Infix("/", untyped, b.untyped))
    }

    /**
      * Models a GLSL bvec2, bvec3 or bvec4
      */
    sealed trait BVec[Self <: BVec[Self]] extends Typed[Self] with XVec[B, BVec2, BVec3, BVec4] {
        protected[Language] val make1 = {u : Untyped => B(u)}
        protected[Language] val make2 = {u : Untyped => BVec2(u)}
        protected[Language] val make3 = {u : Untyped => BVec3(u)}
        protected[Language] val make4 = {u : Untyped => BVec4(u)}
    }

    // Concrete types

    /**
      *  Models a GLSL float
      */
    case class R(protected[Language] val untyped : Untyped) extends FloatN[R] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "float"

        def <(b : R) : B = B(Infix("<", untyped, b.untyped))
        def >(b : R) : B = B(Infix(">", untyped, b.untyped))
        def <=(b : R) : B = B(Infix("<=", untyped, b.untyped))
        def >=(b : R) : B = B(Infix(">=", untyped, b.untyped))

        def +[T <: Vec[T]](b : Vec[T]) : T = b.make(Infix("+", untyped, b.untyped))
        def -[T <: Vec[T]](b : Vec[T]) : T = b.make(Infix("-", untyped, b.untyped))
        def *[T <: Vec[T]](b : Vec[T]) : T = b.make(Infix("*", untyped, b.untyped))
        def /[T <: Vec[T]](b : Vec[T]) : T = b.make(Infix("/", untyped, b.untyped))
    }

    // GLSL bool
    case class B(protected[Language] val untyped : Untyped) extends Typed[B] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "bool"

        def unary_!() : B = B(Prefix("!", untyped))
        def &&(b : B) : B = B(Infix("&&", untyped, b.untyped))
        def ||(b : B) : B = B(Infix("||", untyped, b.untyped))
    }

    // GLSL int
    case class I(protected[Language] val untyped : Untyped) extends Typed[I] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "int"
    }

    case class Vec2(protected[Language] val untyped : Untyped) extends Vec[Vec2] with XVec2[R, Vec2, Vec3, Vec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "vec2"
    }

    case class Vec3(protected[Language] val untyped : Untyped) extends Vec[Vec3] with XVec3[R, Vec2, Vec3, Vec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "vec3"
    }

    case class Vec4(protected[Language] val untyped : Untyped) extends Vec[Vec4] with XVec4[R, Vec2, Vec3, Vec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "vec4"
    }

    case class BVec2(protected[Language] val untyped : Untyped) extends BVec[BVec2] with XVec2[B, BVec2, BVec3, BVec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "bvec2"
    }

    case class BVec3(protected[Language] val untyped : Untyped) extends BVec[BVec3] with XVec3[B, BVec2, BVec3, BVec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "bvec3"
    }

    case class BVec4(protected[Language] val untyped : Untyped) extends BVec[BVec4] with XVec4[B, BVec2, BVec3, BVec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "bvec4"
    }

    case class IVec2(protected[Language] val untyped : Untyped) extends IVec[IVec2] with XVec2[I, IVec2, IVec3, IVec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "ivec2"
    }

    case class IVec3(protected[Language] val untyped : Untyped) extends IVec[IVec3] with XVec3[I, IVec2, IVec3, IVec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "ivec3"
    }

    case class IVec4(protected[Language] val untyped : Untyped) extends IVec[IVec4] with XVec4[I, IVec2, IVec3, IVec4] {
        protected[Language] val make = copy _
        protected[Language] val typeName = "ivec4"
    }


    object R {
        def apply(r : Double) : R = R(ConstantFloat(r))
    }

    object B {
        def apply(b : Boolean) : B = B(ConstantBoolean(b))
    }

    object I {
        def apply(i : Int) : I = I(ConstantInt(i))
    }

    object Vec2 {
        def apply(x : R) : Vec2 = Vec2(Call("vec2", List(x.untyped)))
        def apply(x : R, y : R) : Vec2 = Vec2(Call("vec2", List(x.untyped, y.untyped)))
    }

    object Vec3 {
        def apply(x : R) : Vec3 = Vec3(Call("vec3", List(x.untyped)))
        def apply(x : R, y : R, z : R) : Vec3 = Vec3(Call("vec3", List(x.untyped, y.untyped, z.untyped)))
        def apply(xy : Vec2, z : R) : Vec3 = Vec3(Call("vec3", List(xy.untyped, z.untyped)))
        def apply(x : R, yz : Vec2) : Vec3 = Vec3(Call("vec3", List(x.untyped, yz.untyped)))
    }

    object Vec4 {
        def apply(x : R) : Vec4 = Vec4(Call("vec4", List(x.untyped)))
        def apply(x : R, y : R, z : R, w : R) : Vec4 = Vec4(Call("vec4", List(x.untyped, y.untyped, z.untyped, w.untyped)))
        def apply(xy : Vec2, z : R, w : R) : Vec4 = Vec4(Call("vec4", List(xy.untyped, z.untyped, w.untyped)))
        def apply(xy : Vec2, zw : Vec2) : Vec4 = Vec4(Call("vec4", List(xy.untyped, zw.untyped)))
        def apply(x : R, y : R, zw : Vec2) : Vec4 = Vec4(Call("vec4", List(x.untyped, y.untyped, zw.untyped)))
        def apply(xyz : Vec3, w : R) : Vec4 = Vec4(Call("vec4", List(xyz.untyped, w.untyped)))
        def apply(x : R, yzw : Vec3) : Vec4 = Vec4(Call("vec4", List(x.untyped, yzw.untyped)))
    }

    sealed trait XVec2[Self1, Self2, Self3, Self4] extends XVec[Self1, Self2, Self3, Self4] {
        def x : Self1 = make1(Field("x", untyped))
        def y : Self1 = make1(Field("y", untyped))
        def xx : Self2 = make2(Field("xx", untyped))
        def xy : Self2 = make2(Field("xy", untyped))
        def yx : Self2 = make2(Field("yx", untyped))
        def yy : Self2 = make2(Field("yy", untyped))
        def xxx : Self3 = make3(Field("xxx", untyped))
        def xxy : Self3 = make3(Field("xxy", untyped))
        def xyx : Self3 = make3(Field("xyx", untyped))
        def xyy : Self3 = make3(Field("xyy", untyped))
        def yxx : Self3 = make3(Field("yxx", untyped))
        def yxy : Self3 = make3(Field("yxy", untyped))
        def yyx : Self3 = make3(Field("yyx", untyped))
        def yyy : Self3 = make3(Field("yyy", untyped))
        def xxxx : Self4 = make4(Field("xxxx", untyped))
        def xxxy : Self4 = make4(Field("xxxy", untyped))
        def xxyx : Self4 = make4(Field("xxyx", untyped))
        def xxyy : Self4 = make4(Field("xxyy", untyped))
        def xyxx : Self4 = make4(Field("xyxx", untyped))
        def xyxy : Self4 = make4(Field("xyxy", untyped))
        def xyyx : Self4 = make4(Field("xyyx", untyped))
        def xyyy : Self4 = make4(Field("xyyy", untyped))
        def yxxx : Self4 = make4(Field("yxxx", untyped))
        def yxxy : Self4 = make4(Field("yxxy", untyped))
        def yxyx : Self4 = make4(Field("yxyx", untyped))
        def yxyy : Self4 = make4(Field("yxyy", untyped))
        def yyxx : Self4 = make4(Field("yyxx", untyped))
        def yyxy : Self4 = make4(Field("yyxy", untyped))
        def yyyx : Self4 = make4(Field("yyyx", untyped))
        def yyyy : Self4 = make4(Field("yyyy", untyped))

        def r : Self1 = make1(Field("r", untyped))
        def g : Self1 = make1(Field("g", untyped))
        def rr : Self2 = make2(Field("rr", untyped))
        def rg : Self2 = make2(Field("rg", untyped))
        def gr : Self2 = make2(Field("gr", untyped))
        def gg : Self2 = make2(Field("gg", untyped))
        def rrr : Self3 = make3(Field("rrr", untyped))
        def rrg : Self3 = make3(Field("rrg", untyped))
        def rgr : Self3 = make3(Field("rgr", untyped))
        def rgg : Self3 = make3(Field("rgg", untyped))
        def grr : Self3 = make3(Field("grr", untyped))
        def grg : Self3 = make3(Field("grg", untyped))
        def ggr : Self3 = make3(Field("ggr", untyped))
        def ggg : Self3 = make3(Field("ggg", untyped))
        def rrrr : Self4 = make4(Field("rrrr", untyped))
        def rrrg : Self4 = make4(Field("rrrg", untyped))
        def rrgr : Self4 = make4(Field("rrgr", untyped))
        def rrgg : Self4 = make4(Field("rrgg", untyped))
        def rgrr : Self4 = make4(Field("rgrr", untyped))
        def rgrg : Self4 = make4(Field("rgrg", untyped))
        def rggr : Self4 = make4(Field("rggr", untyped))
        def rggg : Self4 = make4(Field("rggg", untyped))
        def grrr : Self4 = make4(Field("grrr", untyped))
        def grrg : Self4 = make4(Field("grrg", untyped))
        def grgr : Self4 = make4(Field("grgr", untyped))
        def grgg : Self4 = make4(Field("grgg", untyped))
        def ggrr : Self4 = make4(Field("ggrr", untyped))
        def ggrg : Self4 = make4(Field("ggrg", untyped))
        def gggr : Self4 = make4(Field("gggr", untyped))
        def gggg : Self4 = make4(Field("gggg", untyped))

        def s : Self1 = make1(Field("s", untyped))
        def t : Self1 = make1(Field("t", untyped))
        def ss : Self2 = make2(Field("ss", untyped))
        def st : Self2 = make2(Field("st", untyped))
        def ts : Self2 = make2(Field("ts", untyped))
        def tt : Self2 = make2(Field("tt", untyped))
        def sss : Self3 = make3(Field("sss", untyped))
        def sst : Self3 = make3(Field("sst", untyped))
        def sts : Self3 = make3(Field("sts", untyped))
        def stt : Self3 = make3(Field("stt", untyped))
        def tss : Self3 = make3(Field("tss", untyped))
        def tst : Self3 = make3(Field("tst", untyped))
        def tts : Self3 = make3(Field("tts", untyped))
        def ttt : Self3 = make3(Field("ttt", untyped))
        def ssss : Self4 = make4(Field("ssss", untyped))
        def ssst : Self4 = make4(Field("ssst", untyped))
        def ssts : Self4 = make4(Field("ssts", untyped))
        def sstt : Self4 = make4(Field("sstt", untyped))
        def stss : Self4 = make4(Field("stss", untyped))
        def stst : Self4 = make4(Field("stst", untyped))
        def stts : Self4 = make4(Field("stts", untyped))
        def sttt : Self4 = make4(Field("sttt", untyped))
        def tsss : Self4 = make4(Field("tsss", untyped))
        def tsst : Self4 = make4(Field("tsst", untyped))
        def tsts : Self4 = make4(Field("tsts", untyped))
        def tstt : Self4 = make4(Field("tstt", untyped))
        def ttss : Self4 = make4(Field("ttss", untyped))
        def ttst : Self4 = make4(Field("ttst", untyped))
        def ttts : Self4 = make4(Field("ttts", untyped))
        def tttt : Self4 = make4(Field("tttt", untyped))
    }

    sealed trait XVec3[Self1, Self2, Self3, Self4] extends XVec2[Self1, Self2, Self3, Self4] {
        def z : Self1 = make1(Field("z", untyped))
        def xz : Self2 = make2(Field("xz", untyped))
        def yz : Self2 = make2(Field("yz", untyped))
        def zx : Self2 = make2(Field("zx", untyped))
        def zy : Self2 = make2(Field("zy", untyped))
        def zz : Self2 = make2(Field("zz", untyped))
        def xxz : Self3 = make3(Field("xxz", untyped))
        def xyz : Self3 = make3(Field("xyz", untyped))
        def xzx : Self3 = make3(Field("xzx", untyped))
        def xzy : Self3 = make3(Field("xzy", untyped))
        def xzz : Self3 = make3(Field("xzz", untyped))
        def yxz : Self3 = make3(Field("yxz", untyped))
        def yyz : Self3 = make3(Field("yyz", untyped))
        def yzx : Self3 = make3(Field("yzx", untyped))
        def yzy : Self3 = make3(Field("yzy", untyped))
        def yzz : Self3 = make3(Field("yzz", untyped))
        def zxx : Self3 = make3(Field("zxx", untyped))
        def zxy : Self3 = make3(Field("zxy", untyped))
        def zxz : Self3 = make3(Field("zxz", untyped))
        def zyx : Self3 = make3(Field("zyx", untyped))
        def zyy : Self3 = make3(Field("zyy", untyped))
        def zyz : Self3 = make3(Field("zyz", untyped))
        def zzx : Self3 = make3(Field("zzx", untyped))
        def zzy : Self3 = make3(Field("zzy", untyped))
        def zzz : Self3 = make3(Field("zzz", untyped))
        def xxxz : Self4 = make4(Field("xxxz", untyped))
        def xxyz : Self4 = make4(Field("xxyz", untyped))
        def xxzx : Self4 = make4(Field("xxzx", untyped))
        def xxzy : Self4 = make4(Field("xxzy", untyped))
        def xxzz : Self4 = make4(Field("xxzz", untyped))
        def xyxz : Self4 = make4(Field("xyxz", untyped))
        def xyyz : Self4 = make4(Field("xyyz", untyped))
        def xyzx : Self4 = make4(Field("xyzx", untyped))
        def xyzy : Self4 = make4(Field("xyzy", untyped))
        def xyzz : Self4 = make4(Field("xyzz", untyped))
        def xzxx : Self4 = make4(Field("xzxx", untyped))
        def xzxy : Self4 = make4(Field("xzxy", untyped))
        def xzxz : Self4 = make4(Field("xzxz", untyped))
        def xzyx : Self4 = make4(Field("xzyx", untyped))
        def xzyy : Self4 = make4(Field("xzyy", untyped))
        def xzyz : Self4 = make4(Field("xzyz", untyped))
        def xzzx : Self4 = make4(Field("xzzx", untyped))
        def xzzy : Self4 = make4(Field("xzzy", untyped))
        def xzzz : Self4 = make4(Field("xzzz", untyped))
        def yxxz : Self4 = make4(Field("yxxz", untyped))
        def yxyz : Self4 = make4(Field("yxyz", untyped))
        def yxzx : Self4 = make4(Field("yxzx", untyped))
        def yxzy : Self4 = make4(Field("yxzy", untyped))
        def yxzz : Self4 = make4(Field("yxzz", untyped))
        def yyxz : Self4 = make4(Field("yyxz", untyped))
        def yyyz : Self4 = make4(Field("yyyz", untyped))
        def yyzx : Self4 = make4(Field("yyzx", untyped))
        def yyzy : Self4 = make4(Field("yyzy", untyped))
        def yyzz : Self4 = make4(Field("yyzz", untyped))
        def yzxx : Self4 = make4(Field("yzxx", untyped))
        def yzxy : Self4 = make4(Field("yzxy", untyped))
        def yzxz : Self4 = make4(Field("yzxz", untyped))
        def yzyx : Self4 = make4(Field("yzyx", untyped))
        def yzyy : Self4 = make4(Field("yzyy", untyped))
        def yzyz : Self4 = make4(Field("yzyz", untyped))
        def yzzx : Self4 = make4(Field("yzzx", untyped))
        def yzzy : Self4 = make4(Field("yzzy", untyped))
        def yzzz : Self4 = make4(Field("yzzz", untyped))
        def zxxx : Self4 = make4(Field("zxxx", untyped))
        def zxxy : Self4 = make4(Field("zxxy", untyped))
        def zxxz : Self4 = make4(Field("zxxz", untyped))
        def zxyx : Self4 = make4(Field("zxyx", untyped))
        def zxyy : Self4 = make4(Field("zxyy", untyped))
        def zxyz : Self4 = make4(Field("zxyz", untyped))
        def zxzx : Self4 = make4(Field("zxzx", untyped))
        def zxzy : Self4 = make4(Field("zxzy", untyped))
        def zxzz : Self4 = make4(Field("zxzz", untyped))
        def zyxx : Self4 = make4(Field("zyxx", untyped))
        def zyxy : Self4 = make4(Field("zyxy", untyped))
        def zyxz : Self4 = make4(Field("zyxz", untyped))
        def zyyx : Self4 = make4(Field("zyyx", untyped))
        def zyyy : Self4 = make4(Field("zyyy", untyped))
        def zyyz : Self4 = make4(Field("zyyz", untyped))
        def zyzx : Self4 = make4(Field("zyzx", untyped))
        def zyzy : Self4 = make4(Field("zyzy", untyped))
        def zyzz : Self4 = make4(Field("zyzz", untyped))
        def zzxx : Self4 = make4(Field("zzxx", untyped))
        def zzxy : Self4 = make4(Field("zzxy", untyped))
        def zzxz : Self4 = make4(Field("zzxz", untyped))
        def zzyx : Self4 = make4(Field("zzyx", untyped))
        def zzyy : Self4 = make4(Field("zzyy", untyped))
        def zzyz : Self4 = make4(Field("zzyz", untyped))
        def zzzx : Self4 = make4(Field("zzzx", untyped))
        def zzzy : Self4 = make4(Field("zzzy", untyped))
        def zzzz : Self4 = make4(Field("zzzz", untyped))

        def b : Self1 = make1(Field("b", untyped))
        def rb : Self2 = make2(Field("rb", untyped))
        def gb : Self2 = make2(Field("gb", untyped))
        def br : Self2 = make2(Field("br", untyped))
        def bg : Self2 = make2(Field("bg", untyped))
        def bb : Self2 = make2(Field("bb", untyped))
        def rrb : Self3 = make3(Field("rrb", untyped))
        def rgb : Self3 = make3(Field("rgb", untyped))
        def rbr : Self3 = make3(Field("rbr", untyped))
        def rbg : Self3 = make3(Field("rbg", untyped))
        def rbb : Self3 = make3(Field("rbb", untyped))
        def grb : Self3 = make3(Field("grb", untyped))
        def ggb : Self3 = make3(Field("ggb", untyped))
        def gbr : Self3 = make3(Field("gbr", untyped))
        def gbg : Self3 = make3(Field("gbg", untyped))
        def gbb : Self3 = make3(Field("gbb", untyped))
        def brr : Self3 = make3(Field("brr", untyped))
        def brg : Self3 = make3(Field("brg", untyped))
        def brb : Self3 = make3(Field("brb", untyped))
        def bgr : Self3 = make3(Field("bgr", untyped))
        def bgg : Self3 = make3(Field("bgg", untyped))
        def bgb : Self3 = make3(Field("bgb", untyped))
        def bbr : Self3 = make3(Field("bbr", untyped))
        def bbg : Self3 = make3(Field("bbg", untyped))
        def bbb : Self3 = make3(Field("bbb", untyped))
        def rrrb : Self4 = make4(Field("rrrb", untyped))
        def rrgb : Self4 = make4(Field("rrgb", untyped))
        def rrbr : Self4 = make4(Field("rrbr", untyped))
        def rrbg : Self4 = make4(Field("rrbg", untyped))
        def rrbb : Self4 = make4(Field("rrbb", untyped))
        def rgrb : Self4 = make4(Field("rgrb", untyped))
        def rggb : Self4 = make4(Field("rggb", untyped))
        def rgbr : Self4 = make4(Field("rgbr", untyped))
        def rgbg : Self4 = make4(Field("rgbg", untyped))
        def rgbb : Self4 = make4(Field("rgbb", untyped))
        def rbrr : Self4 = make4(Field("rbrr", untyped))
        def rbrg : Self4 = make4(Field("rbrg", untyped))
        def rbrb : Self4 = make4(Field("rbrb", untyped))
        def rbgr : Self4 = make4(Field("rbgr", untyped))
        def rbgg : Self4 = make4(Field("rbgg", untyped))
        def rbgb : Self4 = make4(Field("rbgb", untyped))
        def rbbr : Self4 = make4(Field("rbbr", untyped))
        def rbbg : Self4 = make4(Field("rbbg", untyped))
        def rbbb : Self4 = make4(Field("rbbb", untyped))
        def grrb : Self4 = make4(Field("grrb", untyped))
        def grgb : Self4 = make4(Field("grgb", untyped))
        def grbr : Self4 = make4(Field("grbr", untyped))
        def grbg : Self4 = make4(Field("grbg", untyped))
        def grbb : Self4 = make4(Field("grbb", untyped))
        def ggrb : Self4 = make4(Field("ggrb", untyped))
        def gggb : Self4 = make4(Field("gggb", untyped))
        def ggbr : Self4 = make4(Field("ggbr", untyped))
        def ggbg : Self4 = make4(Field("ggbg", untyped))
        def ggbb : Self4 = make4(Field("ggbb", untyped))
        def gbrr : Self4 = make4(Field("gbrr", untyped))
        def gbrg : Self4 = make4(Field("gbrg", untyped))
        def gbrb : Self4 = make4(Field("gbrb", untyped))
        def gbgr : Self4 = make4(Field("gbgr", untyped))
        def gbgg : Self4 = make4(Field("gbgg", untyped))
        def gbgb : Self4 = make4(Field("gbgb", untyped))
        def gbbr : Self4 = make4(Field("gbbr", untyped))
        def gbbg : Self4 = make4(Field("gbbg", untyped))
        def gbbb : Self4 = make4(Field("gbbb", untyped))
        def brrr : Self4 = make4(Field("brrr", untyped))
        def brrg : Self4 = make4(Field("brrg", untyped))
        def brrb : Self4 = make4(Field("brrb", untyped))
        def brgr : Self4 = make4(Field("brgr", untyped))
        def brgg : Self4 = make4(Field("brgg", untyped))
        def brgb : Self4 = make4(Field("brgb", untyped))
        def brbr : Self4 = make4(Field("brbr", untyped))
        def brbg : Self4 = make4(Field("brbg", untyped))
        def brbb : Self4 = make4(Field("brbb", untyped))
        def bgrr : Self4 = make4(Field("bgrr", untyped))
        def bgrg : Self4 = make4(Field("bgrg", untyped))
        def bgrb : Self4 = make4(Field("bgrb", untyped))
        def bggr : Self4 = make4(Field("bggr", untyped))
        def bggg : Self4 = make4(Field("bggg", untyped))
        def bggb : Self4 = make4(Field("bggb", untyped))
        def bgbr : Self4 = make4(Field("bgbr", untyped))
        def bgbg : Self4 = make4(Field("bgbg", untyped))
        def bgbb : Self4 = make4(Field("bgbb", untyped))
        def bbrr : Self4 = make4(Field("bbrr", untyped))
        def bbrg : Self4 = make4(Field("bbrg", untyped))
        def bbrb : Self4 = make4(Field("bbrb", untyped))
        def bbgr : Self4 = make4(Field("bbgr", untyped))
        def bbgg : Self4 = make4(Field("bbgg", untyped))
        def bbgb : Self4 = make4(Field("bbgb", untyped))
        def bbbr : Self4 = make4(Field("bbbr", untyped))
        def bbbg : Self4 = make4(Field("bbbg", untyped))
        def bbbb : Self4 = make4(Field("bbbb", untyped))

        def p : Self1 = make1(Field("p", untyped))
        def sp : Self2 = make2(Field("sp", untyped))
        def tp : Self2 = make2(Field("tp", untyped))
        def ps : Self2 = make2(Field("ps", untyped))
        def pt : Self2 = make2(Field("pt", untyped))
        def pp : Self2 = make2(Field("pp", untyped))
        def ssp : Self3 = make3(Field("ssp", untyped))
        def stp : Self3 = make3(Field("stp", untyped))
        def sps : Self3 = make3(Field("sps", untyped))
        def spt : Self3 = make3(Field("spt", untyped))
        def spp : Self3 = make3(Field("spp", untyped))
        def tsp : Self3 = make3(Field("tsp", untyped))
        def ttp : Self3 = make3(Field("ttp", untyped))
        def tps : Self3 = make3(Field("tps", untyped))
        def tpt : Self3 = make3(Field("tpt", untyped))
        def tpp : Self3 = make3(Field("tpp", untyped))
        def pss : Self3 = make3(Field("pss", untyped))
        def pst : Self3 = make3(Field("pst", untyped))
        def psp : Self3 = make3(Field("psp", untyped))
        def pts : Self3 = make3(Field("pts", untyped))
        def ptt : Self3 = make3(Field("ptt", untyped))
        def ptp : Self3 = make3(Field("ptp", untyped))
        def pps : Self3 = make3(Field("pps", untyped))
        def ppt : Self3 = make3(Field("ppt", untyped))
        def ppp : Self3 = make3(Field("ppp", untyped))
        def sssp : Self4 = make4(Field("sssp", untyped))
        def sstp : Self4 = make4(Field("sstp", untyped))
        def ssps : Self4 = make4(Field("ssps", untyped))
        def sspt : Self4 = make4(Field("sspt", untyped))
        def sspp : Self4 = make4(Field("sspp", untyped))
        def stsp : Self4 = make4(Field("stsp", untyped))
        def sttp : Self4 = make4(Field("sttp", untyped))
        def stps : Self4 = make4(Field("stps", untyped))
        def stpt : Self4 = make4(Field("stpt", untyped))
        def stpp : Self4 = make4(Field("stpp", untyped))
        def spss : Self4 = make4(Field("spss", untyped))
        def spst : Self4 = make4(Field("spst", untyped))
        def spsp : Self4 = make4(Field("spsp", untyped))
        def spts : Self4 = make4(Field("spts", untyped))
        def sptt : Self4 = make4(Field("sptt", untyped))
        def sptp : Self4 = make4(Field("sptp", untyped))
        def spps : Self4 = make4(Field("spps", untyped))
        def sppt : Self4 = make4(Field("sppt", untyped))
        def sppp : Self4 = make4(Field("sppp", untyped))
        def tssp : Self4 = make4(Field("tssp", untyped))
        def tstp : Self4 = make4(Field("tstp", untyped))
        def tsps : Self4 = make4(Field("tsps", untyped))
        def tspt : Self4 = make4(Field("tspt", untyped))
        def tspp : Self4 = make4(Field("tspp", untyped))
        def ttsp : Self4 = make4(Field("ttsp", untyped))
        def tttp : Self4 = make4(Field("tttp", untyped))
        def ttps : Self4 = make4(Field("ttps", untyped))
        def ttpt : Self4 = make4(Field("ttpt", untyped))
        def ttpp : Self4 = make4(Field("ttpp", untyped))
        def tpss : Self4 = make4(Field("tpss", untyped))
        def tpst : Self4 = make4(Field("tpst", untyped))
        def tpsp : Self4 = make4(Field("tpsp", untyped))
        def tpts : Self4 = make4(Field("tpts", untyped))
        def tptt : Self4 = make4(Field("tptt", untyped))
        def tptp : Self4 = make4(Field("tptp", untyped))
        def tpps : Self4 = make4(Field("tpps", untyped))
        def tppt : Self4 = make4(Field("tppt", untyped))
        def tppp : Self4 = make4(Field("tppp", untyped))
        def psss : Self4 = make4(Field("psss", untyped))
        def psst : Self4 = make4(Field("psst", untyped))
        def pssp : Self4 = make4(Field("pssp", untyped))
        def psts : Self4 = make4(Field("psts", untyped))
        def pstt : Self4 = make4(Field("pstt", untyped))
        def pstp : Self4 = make4(Field("pstp", untyped))
        def psps : Self4 = make4(Field("psps", untyped))
        def pspt : Self4 = make4(Field("pspt", untyped))
        def pspp : Self4 = make4(Field("pspp", untyped))
        def ptss : Self4 = make4(Field("ptss", untyped))
        def ptst : Self4 = make4(Field("ptst", untyped))
        def ptsp : Self4 = make4(Field("ptsp", untyped))
        def ptts : Self4 = make4(Field("ptts", untyped))
        def pttt : Self4 = make4(Field("pttt", untyped))
        def pttp : Self4 = make4(Field("pttp", untyped))
        def ptps : Self4 = make4(Field("ptps", untyped))
        def ptpt : Self4 = make4(Field("ptpt", untyped))
        def ptpp : Self4 = make4(Field("ptpp", untyped))
        def ppss : Self4 = make4(Field("ppss", untyped))
        def ppst : Self4 = make4(Field("ppst", untyped))
        def ppsp : Self4 = make4(Field("ppsp", untyped))
        def ppts : Self4 = make4(Field("ppts", untyped))
        def pptt : Self4 = make4(Field("pptt", untyped))
        def pptp : Self4 = make4(Field("pptp", untyped))
        def ppps : Self4 = make4(Field("ppps", untyped))
        def pppt : Self4 = make4(Field("pppt", untyped))
        def pppp : Self4 = make4(Field("pppp", untyped))
    }

    sealed trait XVec4[Self1, Self2, Self3, Self4] extends XVec3[Self1, Self2, Self3, Self4] {
        def w : Self1 = make1(Field("w", untyped))
        def xw : Self2 = make2(Field("xw", untyped))
        def yw : Self2 = make2(Field("yw", untyped))
        def zw : Self2 = make2(Field("zw", untyped))
        def wx : Self2 = make2(Field("wx", untyped))
        def wy : Self2 = make2(Field("wy", untyped))
        def wz : Self2 = make2(Field("wz", untyped))
        def ww : Self2 = make2(Field("ww", untyped))
        def xxw : Self3 = make3(Field("xxw", untyped))
        def xyw : Self3 = make3(Field("xyw", untyped))
        def xzw : Self3 = make3(Field("xzw", untyped))
        def xwx : Self3 = make3(Field("xwx", untyped))
        def xwy : Self3 = make3(Field("xwy", untyped))
        def xwz : Self3 = make3(Field("xwz", untyped))
        def xww : Self3 = make3(Field("xww", untyped))
        def yxw : Self3 = make3(Field("yxw", untyped))
        def yyw : Self3 = make3(Field("yyw", untyped))
        def yzw : Self3 = make3(Field("yzw", untyped))
        def ywx : Self3 = make3(Field("ywx", untyped))
        def ywy : Self3 = make3(Field("ywy", untyped))
        def ywz : Self3 = make3(Field("ywz", untyped))
        def yww : Self3 = make3(Field("yww", untyped))
        def zxw : Self3 = make3(Field("zxw", untyped))
        def zyw : Self3 = make3(Field("zyw", untyped))
        def zzw : Self3 = make3(Field("zzw", untyped))
        def zwx : Self3 = make3(Field("zwx", untyped))
        def zwy : Self3 = make3(Field("zwy", untyped))
        def zwz : Self3 = make3(Field("zwz", untyped))
        def zww : Self3 = make3(Field("zww", untyped))
        def wxx : Self3 = make3(Field("wxx", untyped))
        def wxy : Self3 = make3(Field("wxy", untyped))
        def wxz : Self3 = make3(Field("wxz", untyped))
        def wxw : Self3 = make3(Field("wxw", untyped))
        def wyx : Self3 = make3(Field("wyx", untyped))
        def wyy : Self3 = make3(Field("wyy", untyped))
        def wyz : Self3 = make3(Field("wyz", untyped))
        def wyw : Self3 = make3(Field("wyw", untyped))
        def wzx : Self3 = make3(Field("wzx", untyped))
        def wzy : Self3 = make3(Field("wzy", untyped))
        def wzz : Self3 = make3(Field("wzz", untyped))
        def wzw : Self3 = make3(Field("wzw", untyped))
        def wwx : Self3 = make3(Field("wwx", untyped))
        def wwy : Self3 = make3(Field("wwy", untyped))
        def wwz : Self3 = make3(Field("wwz", untyped))
        def www : Self3 = make3(Field("www", untyped))
        def xxxw : Self4 = make4(Field("xxxw", untyped))
        def xxyw : Self4 = make4(Field("xxyw", untyped))
        def xxzw : Self4 = make4(Field("xxzw", untyped))
        def xxwx : Self4 = make4(Field("xxwx", untyped))
        def xxwy : Self4 = make4(Field("xxwy", untyped))
        def xxwz : Self4 = make4(Field("xxwz", untyped))
        def xxww : Self4 = make4(Field("xxww", untyped))
        def xyxw : Self4 = make4(Field("xyxw", untyped))
        def xyyw : Self4 = make4(Field("xyyw", untyped))
        def xyzw : Self4 = make4(Field("xyzw", untyped))
        def xywx : Self4 = make4(Field("xywx", untyped))
        def xywy : Self4 = make4(Field("xywy", untyped))
        def xywz : Self4 = make4(Field("xywz", untyped))
        def xyww : Self4 = make4(Field("xyww", untyped))
        def xzxw : Self4 = make4(Field("xzxw", untyped))
        def xzyw : Self4 = make4(Field("xzyw", untyped))
        def xzzw : Self4 = make4(Field("xzzw", untyped))
        def xzwx : Self4 = make4(Field("xzwx", untyped))
        def xzwy : Self4 = make4(Field("xzwy", untyped))
        def xzwz : Self4 = make4(Field("xzwz", untyped))
        def xzww : Self4 = make4(Field("xzww", untyped))
        def xwxx : Self4 = make4(Field("xwxx", untyped))
        def xwxy : Self4 = make4(Field("xwxy", untyped))
        def xwxz : Self4 = make4(Field("xwxz", untyped))
        def xwxw : Self4 = make4(Field("xwxw", untyped))
        def xwyx : Self4 = make4(Field("xwyx", untyped))
        def xwyy : Self4 = make4(Field("xwyy", untyped))
        def xwyz : Self4 = make4(Field("xwyz", untyped))
        def xwyw : Self4 = make4(Field("xwyw", untyped))
        def xwzx : Self4 = make4(Field("xwzx", untyped))
        def xwzy : Self4 = make4(Field("xwzy", untyped))
        def xwzz : Self4 = make4(Field("xwzz", untyped))
        def xwzw : Self4 = make4(Field("xwzw", untyped))
        def xwwx : Self4 = make4(Field("xwwx", untyped))
        def xwwy : Self4 = make4(Field("xwwy", untyped))
        def xwwz : Self4 = make4(Field("xwwz", untyped))
        def xwww : Self4 = make4(Field("xwww", untyped))
        def yxxw : Self4 = make4(Field("yxxw", untyped))
        def yxyw : Self4 = make4(Field("yxyw", untyped))
        def yxzw : Self4 = make4(Field("yxzw", untyped))
        def yxwx : Self4 = make4(Field("yxwx", untyped))
        def yxwy : Self4 = make4(Field("yxwy", untyped))
        def yxwz : Self4 = make4(Field("yxwz", untyped))
        def yxww : Self4 = make4(Field("yxww", untyped))
        def yyxw : Self4 = make4(Field("yyxw", untyped))
        def yyyw : Self4 = make4(Field("yyyw", untyped))
        def yyzw : Self4 = make4(Field("yyzw", untyped))
        def yywx : Self4 = make4(Field("yywx", untyped))
        def yywy : Self4 = make4(Field("yywy", untyped))
        def yywz : Self4 = make4(Field("yywz", untyped))
        def yyww : Self4 = make4(Field("yyww", untyped))
        def yzxw : Self4 = make4(Field("yzxw", untyped))
        def yzyw : Self4 = make4(Field("yzyw", untyped))
        def yzzw : Self4 = make4(Field("yzzw", untyped))
        def yzwx : Self4 = make4(Field("yzwx", untyped))
        def yzwy : Self4 = make4(Field("yzwy", untyped))
        def yzwz : Self4 = make4(Field("yzwz", untyped))
        def yzww : Self4 = make4(Field("yzww", untyped))
        def ywxx : Self4 = make4(Field("ywxx", untyped))
        def ywxy : Self4 = make4(Field("ywxy", untyped))
        def ywxz : Self4 = make4(Field("ywxz", untyped))
        def ywxw : Self4 = make4(Field("ywxw", untyped))
        def ywyx : Self4 = make4(Field("ywyx", untyped))
        def ywyy : Self4 = make4(Field("ywyy", untyped))
        def ywyz : Self4 = make4(Field("ywyz", untyped))
        def ywyw : Self4 = make4(Field("ywyw", untyped))
        def ywzx : Self4 = make4(Field("ywzx", untyped))
        def ywzy : Self4 = make4(Field("ywzy", untyped))
        def ywzz : Self4 = make4(Field("ywzz", untyped))
        def ywzw : Self4 = make4(Field("ywzw", untyped))
        def ywwx : Self4 = make4(Field("ywwx", untyped))
        def ywwy : Self4 = make4(Field("ywwy", untyped))
        def ywwz : Self4 = make4(Field("ywwz", untyped))
        def ywww : Self4 = make4(Field("ywww", untyped))
        def zxxw : Self4 = make4(Field("zxxw", untyped))
        def zxyw : Self4 = make4(Field("zxyw", untyped))
        def zxzw : Self4 = make4(Field("zxzw", untyped))
        def zxwx : Self4 = make4(Field("zxwx", untyped))
        def zxwy : Self4 = make4(Field("zxwy", untyped))
        def zxwz : Self4 = make4(Field("zxwz", untyped))
        def zxww : Self4 = make4(Field("zxww", untyped))
        def zyxw : Self4 = make4(Field("zyxw", untyped))
        def zyyw : Self4 = make4(Field("zyyw", untyped))
        def zyzw : Self4 = make4(Field("zyzw", untyped))
        def zywx : Self4 = make4(Field("zywx", untyped))
        def zywy : Self4 = make4(Field("zywy", untyped))
        def zywz : Self4 = make4(Field("zywz", untyped))
        def zyww : Self4 = make4(Field("zyww", untyped))
        def zzxw : Self4 = make4(Field("zzxw", untyped))
        def zzyw : Self4 = make4(Field("zzyw", untyped))
        def zzzw : Self4 = make4(Field("zzzw", untyped))
        def zzwx : Self4 = make4(Field("zzwx", untyped))
        def zzwy : Self4 = make4(Field("zzwy", untyped))
        def zzwz : Self4 = make4(Field("zzwz", untyped))
        def zzww : Self4 = make4(Field("zzww", untyped))
        def zwxx : Self4 = make4(Field("zwxx", untyped))
        def zwxy : Self4 = make4(Field("zwxy", untyped))
        def zwxz : Self4 = make4(Field("zwxz", untyped))
        def zwxw : Self4 = make4(Field("zwxw", untyped))
        def zwyx : Self4 = make4(Field("zwyx", untyped))
        def zwyy : Self4 = make4(Field("zwyy", untyped))
        def zwyz : Self4 = make4(Field("zwyz", untyped))
        def zwyw : Self4 = make4(Field("zwyw", untyped))
        def zwzx : Self4 = make4(Field("zwzx", untyped))
        def zwzy : Self4 = make4(Field("zwzy", untyped))
        def zwzz : Self4 = make4(Field("zwzz", untyped))
        def zwzw : Self4 = make4(Field("zwzw", untyped))
        def zwwx : Self4 = make4(Field("zwwx", untyped))
        def zwwy : Self4 = make4(Field("zwwy", untyped))
        def zwwz : Self4 = make4(Field("zwwz", untyped))
        def zwww : Self4 = make4(Field("zwww", untyped))
        def wxxx : Self4 = make4(Field("wxxx", untyped))
        def wxxy : Self4 = make4(Field("wxxy", untyped))
        def wxxz : Self4 = make4(Field("wxxz", untyped))
        def wxxw : Self4 = make4(Field("wxxw", untyped))
        def wxyx : Self4 = make4(Field("wxyx", untyped))
        def wxyy : Self4 = make4(Field("wxyy", untyped))
        def wxyz : Self4 = make4(Field("wxyz", untyped))
        def wxyw : Self4 = make4(Field("wxyw", untyped))
        def wxzx : Self4 = make4(Field("wxzx", untyped))
        def wxzy : Self4 = make4(Field("wxzy", untyped))
        def wxzz : Self4 = make4(Field("wxzz", untyped))
        def wxzw : Self4 = make4(Field("wxzw", untyped))
        def wxwx : Self4 = make4(Field("wxwx", untyped))
        def wxwy : Self4 = make4(Field("wxwy", untyped))
        def wxwz : Self4 = make4(Field("wxwz", untyped))
        def wxww : Self4 = make4(Field("wxww", untyped))
        def wyxx : Self4 = make4(Field("wyxx", untyped))
        def wyxy : Self4 = make4(Field("wyxy", untyped))
        def wyxz : Self4 = make4(Field("wyxz", untyped))
        def wyxw : Self4 = make4(Field("wyxw", untyped))
        def wyyx : Self4 = make4(Field("wyyx", untyped))
        def wyyy : Self4 = make4(Field("wyyy", untyped))
        def wyyz : Self4 = make4(Field("wyyz", untyped))
        def wyyw : Self4 = make4(Field("wyyw", untyped))
        def wyzx : Self4 = make4(Field("wyzx", untyped))
        def wyzy : Self4 = make4(Field("wyzy", untyped))
        def wyzz : Self4 = make4(Field("wyzz", untyped))
        def wyzw : Self4 = make4(Field("wyzw", untyped))
        def wywx : Self4 = make4(Field("wywx", untyped))
        def wywy : Self4 = make4(Field("wywy", untyped))
        def wywz : Self4 = make4(Field("wywz", untyped))
        def wyww : Self4 = make4(Field("wyww", untyped))
        def wzxx : Self4 = make4(Field("wzxx", untyped))
        def wzxy : Self4 = make4(Field("wzxy", untyped))
        def wzxz : Self4 = make4(Field("wzxz", untyped))
        def wzxw : Self4 = make4(Field("wzxw", untyped))
        def wzyx : Self4 = make4(Field("wzyx", untyped))
        def wzyy : Self4 = make4(Field("wzyy", untyped))
        def wzyz : Self4 = make4(Field("wzyz", untyped))
        def wzyw : Self4 = make4(Field("wzyw", untyped))
        def wzzx : Self4 = make4(Field("wzzx", untyped))
        def wzzy : Self4 = make4(Field("wzzy", untyped))
        def wzzz : Self4 = make4(Field("wzzz", untyped))
        def wzzw : Self4 = make4(Field("wzzw", untyped))
        def wzwx : Self4 = make4(Field("wzwx", untyped))
        def wzwy : Self4 = make4(Field("wzwy", untyped))
        def wzwz : Self4 = make4(Field("wzwz", untyped))
        def wzww : Self4 = make4(Field("wzww", untyped))
        def wwxx : Self4 = make4(Field("wwxx", untyped))
        def wwxy : Self4 = make4(Field("wwxy", untyped))
        def wwxz : Self4 = make4(Field("wwxz", untyped))
        def wwxw : Self4 = make4(Field("wwxw", untyped))
        def wwyx : Self4 = make4(Field("wwyx", untyped))
        def wwyy : Self4 = make4(Field("wwyy", untyped))
        def wwyz : Self4 = make4(Field("wwyz", untyped))
        def wwyw : Self4 = make4(Field("wwyw", untyped))
        def wwzx : Self4 = make4(Field("wwzx", untyped))
        def wwzy : Self4 = make4(Field("wwzy", untyped))
        def wwzz : Self4 = make4(Field("wwzz", untyped))
        def wwzw : Self4 = make4(Field("wwzw", untyped))
        def wwwx : Self4 = make4(Field("wwwx", untyped))
        def wwwy : Self4 = make4(Field("wwwy", untyped))
        def wwwz : Self4 = make4(Field("wwwz", untyped))
        def wwww : Self4 = make4(Field("wwww", untyped))

        def a : Self1 = make1(Field("a", untyped))
        def ra : Self2 = make2(Field("ra", untyped))
        def ga : Self2 = make2(Field("ga", untyped))
        def ba : Self2 = make2(Field("ba", untyped))
        def ar : Self2 = make2(Field("ar", untyped))
        def ag : Self2 = make2(Field("ag", untyped))
        def ab : Self2 = make2(Field("ab", untyped))
        def aa : Self2 = make2(Field("aa", untyped))
        def rra : Self3 = make3(Field("rra", untyped))
        def rga : Self3 = make3(Field("rga", untyped))
        def rba : Self3 = make3(Field("rba", untyped))
        def rar : Self3 = make3(Field("rar", untyped))
        def rag : Self3 = make3(Field("rag", untyped))
        def rab : Self3 = make3(Field("rab", untyped))
        def raa : Self3 = make3(Field("raa", untyped))
        def gra : Self3 = make3(Field("gra", untyped))
        def gga : Self3 = make3(Field("gga", untyped))
        def gba : Self3 = make3(Field("gba", untyped))
        def gar : Self3 = make3(Field("gar", untyped))
        def gag : Self3 = make3(Field("gag", untyped))
        def gab : Self3 = make3(Field("gab", untyped))
        def gaa : Self3 = make3(Field("gaa", untyped))
        def bra : Self3 = make3(Field("bra", untyped))
        def bga : Self3 = make3(Field("bga", untyped))
        def bba : Self3 = make3(Field("bba", untyped))
        def bar : Self3 = make3(Field("bar", untyped))
        def bag : Self3 = make3(Field("bag", untyped))
        def bab : Self3 = make3(Field("bab", untyped))
        def baa : Self3 = make3(Field("baa", untyped))
        def arr : Self3 = make3(Field("arr", untyped))
        def arg : Self3 = make3(Field("arg", untyped))
        def arb : Self3 = make3(Field("arb", untyped))
        def ara : Self3 = make3(Field("ara", untyped))
        def agr : Self3 = make3(Field("agr", untyped))
        def agg : Self3 = make3(Field("agg", untyped))
        def agb : Self3 = make3(Field("agb", untyped))
        def aga : Self3 = make3(Field("aga", untyped))
        def abr : Self3 = make3(Field("abr", untyped))
        def abg : Self3 = make3(Field("abg", untyped))
        def abb : Self3 = make3(Field("abb", untyped))
        def aba : Self3 = make3(Field("aba", untyped))
        def aar : Self3 = make3(Field("aar", untyped))
        def aag : Self3 = make3(Field("aag", untyped))
        def aab : Self3 = make3(Field("aab", untyped))
        def aaa : Self3 = make3(Field("aaa", untyped))
        def rrra : Self4 = make4(Field("rrra", untyped))
        def rrga : Self4 = make4(Field("rrga", untyped))
        def rrba : Self4 = make4(Field("rrba", untyped))
        def rrar : Self4 = make4(Field("rrar", untyped))
        def rrag : Self4 = make4(Field("rrag", untyped))
        def rrab : Self4 = make4(Field("rrab", untyped))
        def rraa : Self4 = make4(Field("rraa", untyped))
        def rgra : Self4 = make4(Field("rgra", untyped))
        def rgga : Self4 = make4(Field("rgga", untyped))
        def rgba : Self4 = make4(Field("rgba", untyped))
        def rgar : Self4 = make4(Field("rgar", untyped))
        def rgag : Self4 = make4(Field("rgag", untyped))
        def rgab : Self4 = make4(Field("rgab", untyped))
        def rgaa : Self4 = make4(Field("rgaa", untyped))
        def rbra : Self4 = make4(Field("rbra", untyped))
        def rbga : Self4 = make4(Field("rbga", untyped))
        def rbba : Self4 = make4(Field("rbba", untyped))
        def rbar : Self4 = make4(Field("rbar", untyped))
        def rbag : Self4 = make4(Field("rbag", untyped))
        def rbab : Self4 = make4(Field("rbab", untyped))
        def rbaa : Self4 = make4(Field("rbaa", untyped))
        def rarr : Self4 = make4(Field("rarr", untyped))
        def rarg : Self4 = make4(Field("rarg", untyped))
        def rarb : Self4 = make4(Field("rarb", untyped))
        def rara : Self4 = make4(Field("rara", untyped))
        def ragr : Self4 = make4(Field("ragr", untyped))
        def ragg : Self4 = make4(Field("ragg", untyped))
        def ragb : Self4 = make4(Field("ragb", untyped))
        def raga : Self4 = make4(Field("raga", untyped))
        def rabr : Self4 = make4(Field("rabr", untyped))
        def rabg : Self4 = make4(Field("rabg", untyped))
        def rabb : Self4 = make4(Field("rabb", untyped))
        def raba : Self4 = make4(Field("raba", untyped))
        def raar : Self4 = make4(Field("raar", untyped))
        def raag : Self4 = make4(Field("raag", untyped))
        def raab : Self4 = make4(Field("raab", untyped))
        def raaa : Self4 = make4(Field("raaa", untyped))
        def grra : Self4 = make4(Field("grra", untyped))
        def grga : Self4 = make4(Field("grga", untyped))
        def grba : Self4 = make4(Field("grba", untyped))
        def grar : Self4 = make4(Field("grar", untyped))
        def grag : Self4 = make4(Field("grag", untyped))
        def grab : Self4 = make4(Field("grab", untyped))
        def graa : Self4 = make4(Field("graa", untyped))
        def ggra : Self4 = make4(Field("ggra", untyped))
        def ggga : Self4 = make4(Field("ggga", untyped))
        def ggba : Self4 = make4(Field("ggba", untyped))
        def ggar : Self4 = make4(Field("ggar", untyped))
        def ggag : Self4 = make4(Field("ggag", untyped))
        def ggab : Self4 = make4(Field("ggab", untyped))
        def ggaa : Self4 = make4(Field("ggaa", untyped))
        def gbra : Self4 = make4(Field("gbra", untyped))
        def gbga : Self4 = make4(Field("gbga", untyped))
        def gbba : Self4 = make4(Field("gbba", untyped))
        def gbar : Self4 = make4(Field("gbar", untyped))
        def gbag : Self4 = make4(Field("gbag", untyped))
        def gbab : Self4 = make4(Field("gbab", untyped))
        def gbaa : Self4 = make4(Field("gbaa", untyped))
        def garr : Self4 = make4(Field("garr", untyped))
        def garg : Self4 = make4(Field("garg", untyped))
        def garb : Self4 = make4(Field("garb", untyped))
        def gara : Self4 = make4(Field("gara", untyped))
        def gagr : Self4 = make4(Field("gagr", untyped))
        def gagg : Self4 = make4(Field("gagg", untyped))
        def gagb : Self4 = make4(Field("gagb", untyped))
        def gaga : Self4 = make4(Field("gaga", untyped))
        def gabr : Self4 = make4(Field("gabr", untyped))
        def gabg : Self4 = make4(Field("gabg", untyped))
        def gabb : Self4 = make4(Field("gabb", untyped))
        def gaba : Self4 = make4(Field("gaba", untyped))
        def gaar : Self4 = make4(Field("gaar", untyped))
        def gaag : Self4 = make4(Field("gaag", untyped))
        def gaab : Self4 = make4(Field("gaab", untyped))
        def gaaa : Self4 = make4(Field("gaaa", untyped))
        def brra : Self4 = make4(Field("brra", untyped))
        def brga : Self4 = make4(Field("brga", untyped))
        def brba : Self4 = make4(Field("brba", untyped))
        def brar : Self4 = make4(Field("brar", untyped))
        def brag : Self4 = make4(Field("brag", untyped))
        def brab : Self4 = make4(Field("brab", untyped))
        def braa : Self4 = make4(Field("braa", untyped))
        def bgra : Self4 = make4(Field("bgra", untyped))
        def bgga : Self4 = make4(Field("bgga", untyped))
        def bgba : Self4 = make4(Field("bgba", untyped))
        def bgar : Self4 = make4(Field("bgar", untyped))
        def bgag : Self4 = make4(Field("bgag", untyped))
        def bgab : Self4 = make4(Field("bgab", untyped))
        def bgaa : Self4 = make4(Field("bgaa", untyped))
        def bbra : Self4 = make4(Field("bbra", untyped))
        def bbga : Self4 = make4(Field("bbga", untyped))
        def bbba : Self4 = make4(Field("bbba", untyped))
        def bbar : Self4 = make4(Field("bbar", untyped))
        def bbag : Self4 = make4(Field("bbag", untyped))
        def bbab : Self4 = make4(Field("bbab", untyped))
        def bbaa : Self4 = make4(Field("bbaa", untyped))
        def barr : Self4 = make4(Field("barr", untyped))
        def barg : Self4 = make4(Field("barg", untyped))
        def barb : Self4 = make4(Field("barb", untyped))
        def bara : Self4 = make4(Field("bara", untyped))
        def bagr : Self4 = make4(Field("bagr", untyped))
        def bagg : Self4 = make4(Field("bagg", untyped))
        def bagb : Self4 = make4(Field("bagb", untyped))
        def baga : Self4 = make4(Field("baga", untyped))
        def babr : Self4 = make4(Field("babr", untyped))
        def babg : Self4 = make4(Field("babg", untyped))
        def babb : Self4 = make4(Field("babb", untyped))
        def baba : Self4 = make4(Field("baba", untyped))
        def baar : Self4 = make4(Field("baar", untyped))
        def baag : Self4 = make4(Field("baag", untyped))
        def baab : Self4 = make4(Field("baab", untyped))
        def baaa : Self4 = make4(Field("baaa", untyped))
        def arrr : Self4 = make4(Field("arrr", untyped))
        def arrg : Self4 = make4(Field("arrg", untyped))
        def arrb : Self4 = make4(Field("arrb", untyped))
        def arra : Self4 = make4(Field("arra", untyped))
        def argr : Self4 = make4(Field("argr", untyped))
        def argg : Self4 = make4(Field("argg", untyped))
        def argb : Self4 = make4(Field("argb", untyped))
        def arga : Self4 = make4(Field("arga", untyped))
        def arbr : Self4 = make4(Field("arbr", untyped))
        def arbg : Self4 = make4(Field("arbg", untyped))
        def arbb : Self4 = make4(Field("arbb", untyped))
        def arba : Self4 = make4(Field("arba", untyped))
        def arar : Self4 = make4(Field("arar", untyped))
        def arag : Self4 = make4(Field("arag", untyped))
        def arab : Self4 = make4(Field("arab", untyped))
        def araa : Self4 = make4(Field("araa", untyped))
        def agrr : Self4 = make4(Field("agrr", untyped))
        def agrg : Self4 = make4(Field("agrg", untyped))
        def agrb : Self4 = make4(Field("agrb", untyped))
        def agra : Self4 = make4(Field("agra", untyped))
        def aggr : Self4 = make4(Field("aggr", untyped))
        def aggg : Self4 = make4(Field("aggg", untyped))
        def aggb : Self4 = make4(Field("aggb", untyped))
        def agga : Self4 = make4(Field("agga", untyped))
        def agbr : Self4 = make4(Field("agbr", untyped))
        def agbg : Self4 = make4(Field("agbg", untyped))
        def agbb : Self4 = make4(Field("agbb", untyped))
        def agba : Self4 = make4(Field("agba", untyped))
        def agar : Self4 = make4(Field("agar", untyped))
        def agag : Self4 = make4(Field("agag", untyped))
        def agab : Self4 = make4(Field("agab", untyped))
        def agaa : Self4 = make4(Field("agaa", untyped))
        def abrr : Self4 = make4(Field("abrr", untyped))
        def abrg : Self4 = make4(Field("abrg", untyped))
        def abrb : Self4 = make4(Field("abrb", untyped))
        def abra : Self4 = make4(Field("abra", untyped))
        def abgr : Self4 = make4(Field("abgr", untyped))
        def abgg : Self4 = make4(Field("abgg", untyped))
        def abgb : Self4 = make4(Field("abgb", untyped))
        def abga : Self4 = make4(Field("abga", untyped))
        def abbr : Self4 = make4(Field("abbr", untyped))
        def abbg : Self4 = make4(Field("abbg", untyped))
        def abbb : Self4 = make4(Field("abbb", untyped))
        def abba : Self4 = make4(Field("abba", untyped))
        def abar : Self4 = make4(Field("abar", untyped))
        def abag : Self4 = make4(Field("abag", untyped))
        def abab : Self4 = make4(Field("abab", untyped))
        def abaa : Self4 = make4(Field("abaa", untyped))
        def aarr : Self4 = make4(Field("aarr", untyped))
        def aarg : Self4 = make4(Field("aarg", untyped))
        def aarb : Self4 = make4(Field("aarb", untyped))
        def aara : Self4 = make4(Field("aara", untyped))
        def aagr : Self4 = make4(Field("aagr", untyped))
        def aagg : Self4 = make4(Field("aagg", untyped))
        def aagb : Self4 = make4(Field("aagb", untyped))
        def aaga : Self4 = make4(Field("aaga", untyped))
        def aabr : Self4 = make4(Field("aabr", untyped))
        def aabg : Self4 = make4(Field("aabg", untyped))
        def aabb : Self4 = make4(Field("aabb", untyped))
        def aaba : Self4 = make4(Field("aaba", untyped))
        def aaar : Self4 = make4(Field("aaar", untyped))
        def aaag : Self4 = make4(Field("aaag", untyped))
        def aaab : Self4 = make4(Field("aaab", untyped))
        def aaaa : Self4 = make4(Field("aaaa", untyped))

        def q : Self1 = make1(Field("q", untyped))
        def sq : Self2 = make2(Field("sq", untyped))
        def tq : Self2 = make2(Field("tq", untyped))
        def pq : Self2 = make2(Field("pq", untyped))
        def qs : Self2 = make2(Field("qs", untyped))
        def qt : Self2 = make2(Field("qt", untyped))
        def qp : Self2 = make2(Field("qp", untyped))
        def qq : Self2 = make2(Field("qq", untyped))
        def ssq : Self3 = make3(Field("ssq", untyped))
        def stq : Self3 = make3(Field("stq", untyped))
        def spq : Self3 = make3(Field("spq", untyped))
        def sqs : Self3 = make3(Field("sqs", untyped))
        def sqt : Self3 = make3(Field("sqt", untyped))
        def sqp : Self3 = make3(Field("sqp", untyped))
        def sqq : Self3 = make3(Field("sqq", untyped))
        def tsq : Self3 = make3(Field("tsq", untyped))
        def ttq : Self3 = make3(Field("ttq", untyped))
        def tpq : Self3 = make3(Field("tpq", untyped))
        def tqs : Self3 = make3(Field("tqs", untyped))
        def tqt : Self3 = make3(Field("tqt", untyped))
        def tqp : Self3 = make3(Field("tqp", untyped))
        def tqq : Self3 = make3(Field("tqq", untyped))
        def psq : Self3 = make3(Field("psq", untyped))
        def ptq : Self3 = make3(Field("ptq", untyped))
        def ppq : Self3 = make3(Field("ppq", untyped))
        def pqs : Self3 = make3(Field("pqs", untyped))
        def pqt : Self3 = make3(Field("pqt", untyped))
        def pqp : Self3 = make3(Field("pqp", untyped))
        def pqq : Self3 = make3(Field("pqq", untyped))
        def qss : Self3 = make3(Field("qss", untyped))
        def qst : Self3 = make3(Field("qst", untyped))
        def qsp : Self3 = make3(Field("qsp", untyped))
        def qsq : Self3 = make3(Field("qsq", untyped))
        def qts : Self3 = make3(Field("qts", untyped))
        def qtt : Self3 = make3(Field("qtt", untyped))
        def qtp : Self3 = make3(Field("qtp", untyped))
        def qtq : Self3 = make3(Field("qtq", untyped))
        def qps : Self3 = make3(Field("qps", untyped))
        def qpt : Self3 = make3(Field("qpt", untyped))
        def qpp : Self3 = make3(Field("qpp", untyped))
        def qpq : Self3 = make3(Field("qpq", untyped))
        def qqs : Self3 = make3(Field("qqs", untyped))
        def qqt : Self3 = make3(Field("qqt", untyped))
        def qqp : Self3 = make3(Field("qqp", untyped))
        def qqq : Self3 = make3(Field("qqq", untyped))
        def sssq : Self4 = make4(Field("sssq", untyped))
        def sstq : Self4 = make4(Field("sstq", untyped))
        def sspq : Self4 = make4(Field("sspq", untyped))
        def ssqs : Self4 = make4(Field("ssqs", untyped))
        def ssqt : Self4 = make4(Field("ssqt", untyped))
        def ssqp : Self4 = make4(Field("ssqp", untyped))
        def ssqq : Self4 = make4(Field("ssqq", untyped))
        def stsq : Self4 = make4(Field("stsq", untyped))
        def sttq : Self4 = make4(Field("sttq", untyped))
        def stpq : Self4 = make4(Field("stpq", untyped))
        def stqs : Self4 = make4(Field("stqs", untyped))
        def stqt : Self4 = make4(Field("stqt", untyped))
        def stqp : Self4 = make4(Field("stqp", untyped))
        def stqq : Self4 = make4(Field("stqq", untyped))
        def spsq : Self4 = make4(Field("spsq", untyped))
        def sptq : Self4 = make4(Field("sptq", untyped))
        def sppq : Self4 = make4(Field("sppq", untyped))
        def spqs : Self4 = make4(Field("spqs", untyped))
        def spqt : Self4 = make4(Field("spqt", untyped))
        def spqp : Self4 = make4(Field("spqp", untyped))
        def spqq : Self4 = make4(Field("spqq", untyped))
        def sqss : Self4 = make4(Field("sqss", untyped))
        def sqst : Self4 = make4(Field("sqst", untyped))
        def sqsp : Self4 = make4(Field("sqsp", untyped))
        def sqsq : Self4 = make4(Field("sqsq", untyped))
        def sqts : Self4 = make4(Field("sqts", untyped))
        def sqtt : Self4 = make4(Field("sqtt", untyped))
        def sqtp : Self4 = make4(Field("sqtp", untyped))
        def sqtq : Self4 = make4(Field("sqtq", untyped))
        def sqps : Self4 = make4(Field("sqps", untyped))
        def sqpt : Self4 = make4(Field("sqpt", untyped))
        def sqpp : Self4 = make4(Field("sqpp", untyped))
        def sqpq : Self4 = make4(Field("sqpq", untyped))
        def sqqs : Self4 = make4(Field("sqqs", untyped))
        def sqqt : Self4 = make4(Field("sqqt", untyped))
        def sqqp : Self4 = make4(Field("sqqp", untyped))
        def sqqq : Self4 = make4(Field("sqqq", untyped))
        def tssq : Self4 = make4(Field("tssq", untyped))
        def tstq : Self4 = make4(Field("tstq", untyped))
        def tspq : Self4 = make4(Field("tspq", untyped))
        def tsqs : Self4 = make4(Field("tsqs", untyped))
        def tsqt : Self4 = make4(Field("tsqt", untyped))
        def tsqp : Self4 = make4(Field("tsqp", untyped))
        def tsqq : Self4 = make4(Field("tsqq", untyped))
        def ttsq : Self4 = make4(Field("ttsq", untyped))
        def tttq : Self4 = make4(Field("tttq", untyped))
        def ttpq : Self4 = make4(Field("ttpq", untyped))
        def ttqs : Self4 = make4(Field("ttqs", untyped))
        def ttqt : Self4 = make4(Field("ttqt", untyped))
        def ttqp : Self4 = make4(Field("ttqp", untyped))
        def ttqq : Self4 = make4(Field("ttqq", untyped))
        def tpsq : Self4 = make4(Field("tpsq", untyped))
        def tptq : Self4 = make4(Field("tptq", untyped))
        def tppq : Self4 = make4(Field("tppq", untyped))
        def tpqs : Self4 = make4(Field("tpqs", untyped))
        def tpqt : Self4 = make4(Field("tpqt", untyped))
        def tpqp : Self4 = make4(Field("tpqp", untyped))
        def tpqq : Self4 = make4(Field("tpqq", untyped))
        def tqss : Self4 = make4(Field("tqss", untyped))
        def tqst : Self4 = make4(Field("tqst", untyped))
        def tqsp : Self4 = make4(Field("tqsp", untyped))
        def tqsq : Self4 = make4(Field("tqsq", untyped))
        def tqts : Self4 = make4(Field("tqts", untyped))
        def tqtt : Self4 = make4(Field("tqtt", untyped))
        def tqtp : Self4 = make4(Field("tqtp", untyped))
        def tqtq : Self4 = make4(Field("tqtq", untyped))
        def tqps : Self4 = make4(Field("tqps", untyped))
        def tqpt : Self4 = make4(Field("tqpt", untyped))
        def tqpp : Self4 = make4(Field("tqpp", untyped))
        def tqpq : Self4 = make4(Field("tqpq", untyped))
        def tqqs : Self4 = make4(Field("tqqs", untyped))
        def tqqt : Self4 = make4(Field("tqqt", untyped))
        def tqqp : Self4 = make4(Field("tqqp", untyped))
        def tqqq : Self4 = make4(Field("tqqq", untyped))
        def pssq : Self4 = make4(Field("pssq", untyped))
        def pstq : Self4 = make4(Field("pstq", untyped))
        def pspq : Self4 = make4(Field("pspq", untyped))
        def psqs : Self4 = make4(Field("psqs", untyped))
        def psqt : Self4 = make4(Field("psqt", untyped))
        def psqp : Self4 = make4(Field("psqp", untyped))
        def psqq : Self4 = make4(Field("psqq", untyped))
        def ptsq : Self4 = make4(Field("ptsq", untyped))
        def pttq : Self4 = make4(Field("pttq", untyped))
        def ptpq : Self4 = make4(Field("ptpq", untyped))
        def ptqs : Self4 = make4(Field("ptqs", untyped))
        def ptqt : Self4 = make4(Field("ptqt", untyped))
        def ptqp : Self4 = make4(Field("ptqp", untyped))
        def ptqq : Self4 = make4(Field("ptqq", untyped))
        def ppsq : Self4 = make4(Field("ppsq", untyped))
        def pptq : Self4 = make4(Field("pptq", untyped))
        def pppq : Self4 = make4(Field("pppq", untyped))
        def ppqs : Self4 = make4(Field("ppqs", untyped))
        def ppqt : Self4 = make4(Field("ppqt", untyped))
        def ppqp : Self4 = make4(Field("ppqp", untyped))
        def ppqq : Self4 = make4(Field("ppqq", untyped))
        def pqss : Self4 = make4(Field("pqss", untyped))
        def pqst : Self4 = make4(Field("pqst", untyped))
        def pqsp : Self4 = make4(Field("pqsp", untyped))
        def pqsq : Self4 = make4(Field("pqsq", untyped))
        def pqts : Self4 = make4(Field("pqts", untyped))
        def pqtt : Self4 = make4(Field("pqtt", untyped))
        def pqtp : Self4 = make4(Field("pqtp", untyped))
        def pqtq : Self4 = make4(Field("pqtq", untyped))
        def pqps : Self4 = make4(Field("pqps", untyped))
        def pqpt : Self4 = make4(Field("pqpt", untyped))
        def pqpp : Self4 = make4(Field("pqpp", untyped))
        def pqpq : Self4 = make4(Field("pqpq", untyped))
        def pqqs : Self4 = make4(Field("pqqs", untyped))
        def pqqt : Self4 = make4(Field("pqqt", untyped))
        def pqqp : Self4 = make4(Field("pqqp", untyped))
        def pqqq : Self4 = make4(Field("pqqq", untyped))
        def qsss : Self4 = make4(Field("qsss", untyped))
        def qsst : Self4 = make4(Field("qsst", untyped))
        def qssp : Self4 = make4(Field("qssp", untyped))
        def qssq : Self4 = make4(Field("qssq", untyped))
        def qsts : Self4 = make4(Field("qsts", untyped))
        def qstt : Self4 = make4(Field("qstt", untyped))
        def qstp : Self4 = make4(Field("qstp", untyped))
        def qstq : Self4 = make4(Field("qstq", untyped))
        def qsps : Self4 = make4(Field("qsps", untyped))
        def qspt : Self4 = make4(Field("qspt", untyped))
        def qspp : Self4 = make4(Field("qspp", untyped))
        def qspq : Self4 = make4(Field("qspq", untyped))
        def qsqs : Self4 = make4(Field("qsqs", untyped))
        def qsqt : Self4 = make4(Field("qsqt", untyped))
        def qsqp : Self4 = make4(Field("qsqp", untyped))
        def qsqq : Self4 = make4(Field("qsqq", untyped))
        def qtss : Self4 = make4(Field("qtss", untyped))
        def qtst : Self4 = make4(Field("qtst", untyped))
        def qtsp : Self4 = make4(Field("qtsp", untyped))
        def qtsq : Self4 = make4(Field("qtsq", untyped))
        def qtts : Self4 = make4(Field("qtts", untyped))
        def qttt : Self4 = make4(Field("qttt", untyped))
        def qttp : Self4 = make4(Field("qttp", untyped))
        def qttq : Self4 = make4(Field("qttq", untyped))
        def qtps : Self4 = make4(Field("qtps", untyped))
        def qtpt : Self4 = make4(Field("qtpt", untyped))
        def qtpp : Self4 = make4(Field("qtpp", untyped))
        def qtpq : Self4 = make4(Field("qtpq", untyped))
        def qtqs : Self4 = make4(Field("qtqs", untyped))
        def qtqt : Self4 = make4(Field("qtqt", untyped))
        def qtqp : Self4 = make4(Field("qtqp", untyped))
        def qtqq : Self4 = make4(Field("qtqq", untyped))
        def qpss : Self4 = make4(Field("qpss", untyped))
        def qpst : Self4 = make4(Field("qpst", untyped))
        def qpsp : Self4 = make4(Field("qpsp", untyped))
        def qpsq : Self4 = make4(Field("qpsq", untyped))
        def qpts : Self4 = make4(Field("qpts", untyped))
        def qptt : Self4 = make4(Field("qptt", untyped))
        def qptp : Self4 = make4(Field("qptp", untyped))
        def qptq : Self4 = make4(Field("qptq", untyped))
        def qpps : Self4 = make4(Field("qpps", untyped))
        def qppt : Self4 = make4(Field("qppt", untyped))
        def qppp : Self4 = make4(Field("qppp", untyped))
        def qppq : Self4 = make4(Field("qppq", untyped))
        def qpqs : Self4 = make4(Field("qpqs", untyped))
        def qpqt : Self4 = make4(Field("qpqt", untyped))
        def qpqp : Self4 = make4(Field("qpqp", untyped))
        def qpqq : Self4 = make4(Field("qpqq", untyped))
        def qqss : Self4 = make4(Field("qqss", untyped))
        def qqst : Self4 = make4(Field("qqst", untyped))
        def qqsp : Self4 = make4(Field("qqsp", untyped))
        def qqsq : Self4 = make4(Field("qqsq", untyped))
        def qqts : Self4 = make4(Field("qqts", untyped))
        def qqtt : Self4 = make4(Field("qqtt", untyped))
        def qqtp : Self4 = make4(Field("qqtp", untyped))
        def qqtq : Self4 = make4(Field("qqtq", untyped))
        def qqps : Self4 = make4(Field("qqps", untyped))
        def qqpt : Self4 = make4(Field("qqpt", untyped))
        def qqpp : Self4 = make4(Field("qqpp", untyped))
        def qqpq : Self4 = make4(Field("qqpq", untyped))
        def qqqs : Self4 = make4(Field("qqqs", untyped))
        def qqqt : Self4 = make4(Field("qqqt", untyped))
        def qqqp : Self4 = make4(Field("qqqp", untyped))
        def qqqq : Self4 = make4(Field("qqqq", untyped))
    }
}
